- EXAMPLES.md
- lib/sshkit/backends/local.rb
- lib/sshkit/host.rb
- lib/sshkit/runners/abstract.rb
- test/unit/test_host.rb
This pull request allows `on(:local)` to work as an alias for `run_locally`. The advantage of this feature is that Capistrano can be easily configured to perform actions on the local host or on a server, depending on user input, without having to replace all `on` calls with `run_locally`.
For example (in Capistrano):
if ENV['RUN_LOCALLY']
server :local, :roles => [:app]
else
server "example.com", :roles => [:app]
end
on roles(:app) do
execute :any_command
end
It also makes `download!` and `upload!` work when run locally.
> Allow running local commands using `on(:local)`

- .gitignore
- CHANGELOG.md
- Vagrantfile
- lib/sshkit/backends/netssh.rb
- test/functional/backends/test_netssh.rb
Primarily for capistrano/capistrano#1377 but also includes Vagrant updates
Note that the test `test_execute_raises_on_non_zero_exit_status_and_captures_stdout_and_stderr` exhibits random failures.
> Fix merge ssh options

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
Since SSH channel events are not guaranteed to arrive in sequence, the
exit-status event could precede the extended_data event. Since raising
the exception was triggered by assigning the exit status this would
cause the output of failed command to be empty.
Also explains random failures in the test:
`test_execute_raises_on_non_zero_exit_status_and_captures_stdout_and_stderr`
> Fix race condition in SSH backend

- CHANGELOG.md
- lib/sshkit/exception.rb
Remove backtrace() and backtrace_locations() overrides from
ExecuteError.  Having this interferes with rake default behaviour for
displaying exceptions with causes and creates duplicate and
unnecessarily verbose stacktraces in Capistrano.
> Simplify SSHKit::Runner::ExecuteError

- lib/sshkit/formatters/pretty.rb
Reset command stdout and stderr strings to avoid duplicate messages
Introduced by the race condition fix
Sorry about this! I didn't spot that the DEBUG messages for stdout and stderr were being duplicated..
> Fix duplicate messages

- lib/sshkit/command.rb
Fix omission in an earlier fix for failed command output so that
when an error occurs all the stderr/stdout is placed into the exception
> Place full output in exception on failed command

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
This restores SSHKit 1.6 behavior and ensures that command completion status messages appear in the log output.
Fixes #226.
> Log command *after* setting its exit_status

- lib/sshkit/command.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/formatters/pretty.rb
- lib/sshkit/formatters/simple_text.rb
- test/unit/formatters/test_pretty.rb
- test/unit/formatters/test_simple_text.rb
- test/unit/test_command.rb
This is really preparatory work for supporting pty handlers - #234
This PR grew from me not understanding why [these](https://github.com/capistrano/sshkit/blob/bcbd57f0744f5cfbe2756e779ec882645fcc0e83/lib/sshkit/formatters/pretty.rb#L37) [lines](https://github.com/capistrano/sshkit/blob/bcbd57f0744f5cfbe2756e779ec882645fcc0e83/lib/sshkit/formatters/pretty.rb#L46) that clear stdout/stderr are needed. These were added to as part of #224 to get round a duplicate messages issue, but I wanted to backfill with a failing test so I don't break it when I start fiddling with that code in #234.
I wrote a test case for the `Pretty` formatter in 61e03af which fails with duplicate messages if the clearing lines are deleted, I also noticed that there was no test at all for the `SimpleText` formatter, so …
> Remove duplication in clearing command stdout / stderr

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
- test/functional/backends/test_netssh.rb
This is a breaking change, which I wanted to discuss before merging - I'm not sure what the best course of action is here.
The old `capture` behaviour was to `strip` whitespace and newlines from the captured results. I think the main reason for this was to remove trailing newlines from command results to make one liners easier to handle (eg `capture(:uname)` returns `Linux` as opposed to `Linux\n`). Unfortunately this meant that you couldn't capture command output with trailing whitespace / newlines. This was discussed in #165 with @townsen, and I believe it was decided to make this change, however this was only changed for the `Local` backend in 7d15a9a, but not for the Netssh one. I think this was an omission, so, if possible, I would like to fix this inconsistency now.
From an API …
> No longer strip whitespace/newlines in capture method on Netssh backend

- CHANGELOG.md
- EXAMPLES.md
- README.md
- lib/sshkit/all.rb
- lib/sshkit/backends/abstract.rb
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
- lib/sshkit/backends/skipper.rb
- lib/sshkit/command.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/logger.rb
- lib/sshkit/mapping_interaction_handler.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
- test/unit/backends/test_abstract.rb
- test/unit/formatters/test_pretty.rb
- test/unit/formatters/test_simple_text.rb
- test/unit/test_command.rb
- test/unit/test_logger.rb
- test/unit/test_mapping_interaction_handler.rb
I know there has been a lot of confusion and misunderstanding around the `Netssh.config.pty` option with a lot of people (myself included - sorry!) thinking that interactive sessions are supported in SSHKit. My understanding is that full interactivity support is not a direction SSHKit should go in (I agree). So this is an attempt at implementing a minimal patch to allow users to write their own programmatic, rules-based handlers to support interactive workflows. ie 'When the server responds with x', 'send y'.
This PR adds support for an enhanced `:pty` option on `Command` in addition to the existing global level  `Netssh.config.pty` option. This `:pty` option still supports values of `true` and `false`/`nil` as before, but also now supports passing a handler object which defines …
> Support pty or interaction handlers

- EXAMPLES.md
- README.md
- lib/sshkit/command.rb
- lib/sshkit/mapping_interaction_handler.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
- test/unit/test_mapping_interaction_handler.rb
This PR contains 4 improvements to the `:interaction_handler` option API from trying to use this with Capistrano in the real world:
1) Put the `MappingInteractionHandler` class in the `SSHKit` module
2) Support specifying an `interaction_handler` as a hash
```Ruby
execute(:some_command, interaction_handler: SSHKit::MappingInteractionHandler.new("Some output\n" => "Input\n"))
execute(:some_command, interaction_handler: { "Some output\n" => "Input\n"})
```
3) No longer append a newline to the user input. This removes an inconsistency between the server side and user input side of the mapping:
```Ruby
execute(:some_command, interaction_handler: { "Some output\n" => "Input"})
execute(:some_command, interaction_handler: { "Some output\n" => "Input\n"})
```
4) Remove the`output` constructor …
> Improve interaction handler api

- CHANGELOG.md
- README.md
- lib/sshkit/backends/printer.rb
- lib/sshkit/color.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/formatters/dot.rb
- lib/sshkit/formatters/pretty.rb
- lib/sshkit/formatters/simple_text.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
- test/unit/backends/test_connection_pool.rb
- test/unit/backends/test_printer.rb
- test/unit/formatters/test_dot.rb
- test/unit/formatters/test_pretty.rb
- test/unit/formatters/test_simple_text.rb
- test/unit/test_color.rb
- test/unit/test_coordinator.rb
As discussed in #245, this PR reworks color support so that we don't ouput ANSI color escape sequences for output IOs which aren't associated with a tty.
The main rework is to convert the `Color` module into a class which can be instantiated with the output IO, rather than just being hard coded to the `$stdout.tty?`
As part of this change, I was trying to add a test for the colors [in this message](https://github.com/capistrano/sshkit/blob/c9de10d38f5ddb81e8bdbacf58ac4e5094277d03/lib/sshkit/formatters/pretty.rb#L13) in the pretty formatter:
```ruby
c.black(c.on_yellow("Output formatter doesn't know how to handle #{obj.class}\n"))
```
Calling write with an unexpected object type didn't call the above line, but instead raised an exception - (`undefined method 'verbosity' for …
> No colors for non tty outputs

- CHANGELOG.md
- lib/sshkit/all.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/formatters/pretty.rb
- lib/sshkit/formatters/simple_text.rb
- test/unit/formatters/test_pretty.rb
- test/unit/formatters/test_simple_text.rb
This PR is a refactor of the `Pretty` / `SimpleText` formatters to remove the duplication between them. I think this is about as dry as it gets for these 2 classes - now SimpleText only has to override the `format_message` in `Pretty` (to exclude the level, uuid and indentation formatting) and the `colorize` method in `Abstract` (to disable coloring). I think this closes #245 which was about having a way of turning off colors in the `SimpleText` formatter, which we have now achieved.
Team @leehambley & @mattbrictson - if you have time to eyeball, would appreciate it.
> Remove formatter duplication

- BREAKING_API_WISHLIST.md
- CHANGELOG.md
- README.md
- lib/sshkit/backends/abstract.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
- test/unit/backends/test_abstract.rb
I am nervous about the decision we made over in #239, to no longer strip the output of `capture`. Having seen some of the issues that are raised, I think there might be quite a lot of fallout from this. I'm particularly worried that this may not fail in an easy-to-understand way, and that we may waste a lot of everyones time dealing with them. I also think that in many cases, eg the [one liners in Capistrano](https://github.com/mattbrictson/capistrano/commit/ad8682de34ac78ba69da1569fe0fcdfa3014dc6d), stripping is a reasonable default.
I do still think that we should make the API consistent between the `Local` and `NetSSH` backends. Therefore, I'd like to propose that we make stripping whitespace the default, but add an option to the capture method to turn off stripping.
@townsen Would you …
> Add strip option to capture, reinstate stripping by default in the capture methods

- CHANGELOG.md
- lib/sshkit/command.rb
- test/unit/test_command.rb
Ran into an issue this week with an environment variable which contained special shell characters, and broke deploys.
I was going to solve this with `Shellwords.escape`, but found that also escapes '$'.
I ended up taking the approach from #156 and bringing it up to date with master.
@leehambley You okay with this approach?
> Quote environment variable values

- README.md
- lib/sshkit/mapping_interaction_handler.rb
- test/unit/test_mapping_interaction_handler.rb
No longer log by default when using the interaction_handler option in case data is sensitive (passwords etc). Hopefully fixes #251.
> Support log_level constructor parameter for MappingInteractionHandlers

- BREAKING_API_WISHLIST.md
- CHANGELOG.md
- README.md
- lib/sshkit/all.rb
- lib/sshkit/backends/abstract.rb
- lib/sshkit/configuration.rb
- lib/sshkit/deprecation_logger.rb
- test/unit/backends/test_abstract.rb
- test/unit/test_configuration.rb
- test/unit/test_deprecation_logger.rb
Further to #257, this PR adds support for a DeprecationLogger and related configuration.
> Add support for deprecation_output config and DeprecationLogger

- BREAKING_API_WISHLIST.md
- CHANGELOG.md
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
- lib/sshkit/backends/printer.rb
- lib/sshkit/command.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/formatters/black_hole.rb
- lib/sshkit/formatters/dot.rb
- lib/sshkit/formatters/pretty.rb
- test/unit/formatters/test_custom.rb
- test/unit/formatters/test_dot.rb
- test/unit/formatters/test_pretty.rb
- test/unit/formatters/test_simple_text.rb
- test/unit/test_command.rb
At the moment, one of the hardest bits of code to understand, and the source of some historical bugs, is the [`@stdout`, `@stderr`](https://github.com/capistrano/sshkit/blob/1a7c69f56ef8a60c4df5b411124d6c935cefe665/lib/sshkit/command.rb#L28) attributes on command. These are used as a temporary buffer of the latest unconsumed output lines by the formatters. The backends append to the buffer ([netssh](https://github.com/capistrano/sshkit/blob/1a7c69f56ef8a60c4df5b411124d6c935cefe665/lib/sshkit/backends/netssh.rb#L92), [local](https://github.com/capistrano/sshkit/blob/1a7c69f56ef8a60c4df5b411124d6c935cefe665/lib/sshkit/backends/local.rb#L44)) via the [on_stdout](https://github.com/capistrano/sshkit/blob/1a7c69f56ef8a60c4df5b411124d6c935cefe665/lib/sshkit/command.rb#L60) and …
> Introduce explicit command logging methods and deprecate stdout / stderr Command attrs

- CHANGELOG.md
- lib/sshkit/color.rb
- sshkit.gemspec
- test/unit/test_color.rb
I think SSHKit's ANSI color needs are simple enough that we do not need to depend on a third-party gem (colorize). The colorize dependency has been a source of bugs.
Instead, we could implement a simple module that provides various colorizing methods. These methods could be used as module functions, or mixed in to the class where they are needed for convenience.
I did this for airbrussh, and it has worked well so far:
```ruby
module Airbrussh
module Colors
ANSI_CODES = {
:red    => 31,
:green  => 32,
:yellow => 33,
:blue   => 34,
:gray   => 90
}.freeze
module_function
ANSI_CODES.each do |name, code|
define_method(name) do |string|
"\e[0;#{code};49m#{string}\e[0m"
end
end
end
end
```
If there is interest I can create a PR for SSHKit.
> Remove the need for an external dependency for ANSI color

- README.md
- lib/sshkit/command.rb
- lib/sshkit/mapping_interaction_handler.rb
- test/unit/test_mapping_interaction_handler.rb
The current `interaction handler` API is overly complex, requiring users to implement both `on_stdout` and `on_stderr`. In many cases, you don't care which stream the data is arriving on. 
Therefore I propose to replace two methods (`on_stdout` and `on_stderr`) with a single `on_data` method. The `stream_name` (`:stdout` or `:stderr`) is now passed as a parameter so can still be used if the user needs to distinguish between the two.
If people are agreed that the single method API is better, we might as well fix this now before the `interaction_handler` API is officially released.
> Combine on_stdout and on_stderr into on_data on interaction handler api

- CHANGELOG.md
- lib/sshkit/command.rb
- test/functional/backends/test_netssh.rb
- test/unit/test_command.rb
Export environment variables before running a command, allowing for variable substitution in the command itself.
Also enable more flexible command prefixes.
Addresses #270.
> Export environment variables and execute command in a subshell

- CHANGELOG.md
- lib/sshkit/backends/abstract.rb
- lib/sshkit/backends/connection_pool.rb
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
- lib/sshkit/backends/skipper.rb
- lib/sshkit/command.rb
- lib/sshkit/deprecation_logger.rb
- lib/sshkit/formatters/abstract.rb
- lib/sshkit/formatters/black_hole.rb
- lib/sshkit/formatters/dot.rb
- lib/sshkit/formatters/simple_text.rb
- lib/sshkit/host.rb
- lib/sshkit/mapping_interaction_handler.rb
- lib/sshkit/runners/parallel.rb
- lib/sshkit/runners/sequential.rb
- test/functional/backends/test_netssh.rb
- test/helper.rb
- test/unit/backends/test_abstract.rb
- test/unit/backends/test_connection_pool.rb
- test/unit/test_coordinator.rb
- test/unit/test_host.rb
* Prepend unused parameter names with an underscore
* Prefer “safe assignment in condition”
* Disambiguate regexp literals with parens
* Prefer `sprintf` over `String#%`
* No longer shadow `caller_line` variable in `DeprecationLogger`
* Rescue `StandardError` instead of `Exception`
* Remove useless `private` access modifier in `TestAbstract`
* Disambiguate block operator with parens
* Disambiguate between grouped expression and method params
* Remove assertion in `TestHost#test_assert_hosts_compare_equal` that compares something with itself
> Address all rubocop lint warnings

- lib/sshkit/backends/connection_pool.rb
@leehambley @mattbrictson for review
[this line](https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/connection_pool.rb#L19) causes sshkit to call inspect on "new_connection_args" and stringify it. This causes the **memory address** of the proxy object to be included in the hash key, meaning that identical objects that just have a different address won't get a hash hit. This causes it to generate new connections over and over and over as it will never find the connection it's looking for, so it just generates new ones and shoves them in the hash.
For instance:
This key:
```
["SOME_HOST", "deploy", {:user=>"deploy", :forward_agent=>true, :proxy=>#<Net::SSH::Proxy::Command:0x00000000b8c9a0 @command_line_template="ssh deploy@SOME_BASTION nc %h %p", @command_line=nil>}]
``` …
> Monkey patch net-ssh to make hashing scheme work

- CHANGELOG.md
- lib/sshkit/backends/connection_pool.rb
- sshkit.gemspec
- test/unit/backends/test_connection_pool.rb
If sshkit is used not in capistrano but in a daemon, SSH connections are kept in CollectionPool. But there is  no method to close them explicitly, so I added SSHKit::Backend::ConnectionPool#close_connections method to close them.
Suppressed net-ssh version `< 3.0.0` to prevent installing error on ruby 1.9.2 and 1.9.3.
- https://travis-ci.org/capistrano/sshkit/jobs/82688897
- https://travis-ci.org/capistrano/sshkit/jobs/82688898
> add SSHKit::Backend::ConnectionPool#close_connections

- Gemfile
- RELEASING.md
- Rakefile
Chandler is a small gem that plugs into Bundler's `rake release` rake task. Upon successful release to rubygems.org, Chandler will parse the SSHKit CHANGELOG and upload the release notes it finds there to the Releases page on GitHub.
This ensures that the GitHub releases page always has our latest release notes, without requiring tedious copy and paste.
As an example, if you look at the [Releases](https://github.com/capistrano/sshkit/releases) page now, you can see the 1.7.1 release notes. These were parsed from the existing CHANGELOG and uploaded by running `chandler push v1.7.1`. This PR makes this process automatic by doing a `chandler push` whenever we `rake release`.
I made changes to the `RELEASING.md` to explain the prerequisites for using `rake release`. Notably, chandler requires …
> Add chandler to `rake release`; improve docs

- lib/sshkit/configuration.rb
- test/unit/test_configuration.rb
As discussed in https://github.com/mattbrictson/airbrussh/pull/64#issuecomment-152255622, this PR adds a new API for setting the SSHKit output.
Before:
```ruby
SSHKit.config.format = :pretty
```
After:
```ruby
SSHKit.config.use_format :pretty
```
The benefit is that the new `use_format` accepts arbitrary arguments that are then passed to the formatter's constructor. This allows a formatter to be configured.
Hypothetical example:
```ruby
SSHKit.config.use_format :airbrussh, :color => true, :truncate => false
```
This would construct `SSHKit::Formatter::Airbrussh` and pass `{ :color => true, :truncate => false }` to its constructor.
SSHKit's current formatters do not yet accept extra arguments, but this API lays the groundwork for future formatters or formatter gems like airbrussh that are …
> New API for setting+configuring formatter: use_format

- lib/sshkit/configuration.rb
- test/unit/test_configuration.rb
Reverts capistrano/sshkit#294 (prematurely merged)
> Revert "New API for setting+configuring formatter: use_format"

- lib/sshkit/host.rb
- test/unit/test_host.rb
This ensures that the code works on both Unix and Windows, while `Etc.getpwuid` relied on /etc/passwd being present, so it returned a NoMethodError when calling `name` on Windows.
This change has been discussed in capistrano/capistrano#1521.
> Use env vars instead of Etc module for local user lookup

- README.md
Reinstate the doc I accidentally removed in https://github.com/capistrano/sshkit/pull/296#issuecomment-152871755
Good catch, @robd. Sorry about that!
> Reinstate output doc I deleted by mistake

- lib/sshkit/backends/connection_pool.rb
- test/unit/backends/test_connection_pool.rb
Ensure expired pool connections are closed.
I encountered this issue using sshkit with a large number of hosts.  My setup relies on jump hosts. `Net::SSH` is correctly parsing the jump host config from my ~/.ssh/config, and is connecting just fine.  However, since sshkit isn't closing the expired connections, I'm accumulating hundreds/thousands of external processes (the result of `ProxyCommand` in my ~/.ssh/config).  Eventually this starves my system of resources and the ruby process dies.
Anyway, this PR ensures expired connections are closed and pruned at checkout and checkin.  Ultimately the pool might make more sense as an LRU cache with an upper bound on number of entries, but that seemed like too much change at once.
> Close expired pool connections

- CHANGELOG.md
- lib/sshkit/backends/abstract.rb
- test/unit/backends/test_abstract.rb
This might be what was reported in #265. Once a `within` is called and exited, any other mapped commands will execute in the $HOME directory. Still working on tests.
> pwd is an empty array if already instantiated

- CHANGELOG.md
- lib/sshkit/command.rb
- test/unit/backends/test_printer.rb
It seemed odd to see the `/usr/bin/env` prefix when that wasn't the command being run.
> Formatters::Pretty: display command being run

- sshkit.gemspec
- test/functional/backends/test_local.rb
- test/helper.rb
SSHKit was using the `turn` gem, which is no longer maintained. SSHKit was also pinned to a very old version of the minitest gem (released in 2012).
This commit brings SSHKit up to the current 5.x version of minitest, and replaces the turn gem with minitest-reporters, which provides similar rspec-like output with ansi color.
Other changes in minitest 5:
* `MiniTest::Unit::TestCase` is now `Minitest::Test`
* `require 'minitest/autorun'` instead of `MiniTest::Unit.autorun`
Old test output:
```
SSHKit::Backend::TestNetssh
PASS (0:00:00.214) test_netssh_ext
PASS (0:00:00.215) test_net_ssh_configuration_options
PASS (0:00:00.216) test_transfer_summarizer
```
New test output:
```
SSHKit::Backend::TestNetssh
test_net_ssh_configuration_options                              PASS (0.00s) …
```
> Upgrade to minitest 5

- CHANGELOG.md
- README.md
- lib/sshkit/formatters/abstract.rb
- test/unit/formatters/test_custom.rb
This PR adds optional `options` to all Formatters via `Formatter::Abstract`.
None of the built in formatters yet do anything with these options. However, it provides a consistent #initialize API that allows us to promote "formatter options" as a concept further up the stack in Capistrano.
For example, in Capistrano we can offer this configuration system:
```ruby
set :format, ...
set :format_options, key: value, ...
```
We can only reasonable offer this if we are sure that the underlying formatters all accept an options hash (i.e. the :format_options).
Most importantly, Airbrussh *does* have options, and this will allow us to have a standard way for those options to be declared. Airbrussh will be the default formatter in a future version of Capistrano, and this commit is part of laying the …
> Allow all Formatters to accept options hash

- CHANGELOG.md
- lib/sshkit/backends/printer.rb
- test/unit/backends/test_printer.rb
which makes --dry-run pass the `deploy:check:linked_files`
> `SSHKit::Backend::Printer#test` now always returns true

- test/unit/test_host.rb
* Assert all three comparators work (`==`, `eql?`, and `equal`)
> Test that hosts are equal IFF their hashes are equal

- .travis.yml
- CONTRIBUTING.md
- Rakefile
- lib/sshkit/backends/connection_pool.rb
- lib/sshkit/formatters/pretty.rb
- lib/sshkit/mapping_interaction_handler.rb
- sshkit.gemspec
- test/unit/backends/test_connection_pool.rb
- test/unit/formatters/test_custom.rb
I see there is a [precedent](https://github.com/capistrano/sshkit/pull/275) for running RuboCop's lint checks on the SSHKit codebase, so I thought we should make it an official part of the build process.
This PR does the following:
* Fixes all warnings reported by `rubocop --lint` (there were only a few)
* Explains our usage of RuboCop in CONTRIBUTING
* Adds a `lint` rake task for executing `rubocop --lint`
* Makes linting part of the default rake task
* Adds linting to the Travis build
RuboCop's linting rules are not very controversial (I hope!), so I figure this is a good start. We can perhaps add stricter style guidelines in the future if there is interest.
/cc @leehambley @robd @cshaffer
> Add `rubocop --lint` to default rake task and Travis build

- CHANGELOG.md
- lib/sshkit/backends/abstract.rb
- test/unit/backends/test_abstract.rb
This PR adds the `SSHKit::Backend.current` method that I originally introduced in a monkey patch in this Capistrano PR: https://github.com/capistrano/capistrano/pull/1561
> Add SSHKit::Backend.current

- lib/sshkit/backends/netssh.rb
I stumbled upon an interesting issue when converting our deployment scripts from Capistrano v2 to v3, namely with trying to pass SSH options via the global configuration (from capistrano itself). Theoretically the global configuration should be merged into host (server) options before the connection is established, in practice that never happened in my scenario. I tracked it down to a combination of a third party cap plugin and an issue in the SSHKit gem itself.
The third part gem overrides the SSHKit backend in capistrano (which is `SSHKit::Backend::Netssh` by default) to a custom one which inherits from the capistrano default one. The capistrano initializer then sets options - including ssh options - to that class instance. Before establishing the connection, SSHKit now merges those …
> Reference the correct class instance for ssh options merge

- CHANGELOG.md
- lib/sshkit/configuration.rb
- lib/sshkit/coordinator.rb
- test/unit/test_configuration.rb
- test/unit/test_coordinator.rb
This patch enables ability to specify my own runner class.
```ruby
module SSHKit
module Runner
class MyParallel < Abstract
end
end
end
on roles(:web), in: :my_parallel do
end
```
> Ability to specify custom runner

- CHANGELOG.md
- lib/sshkit/command_map.rb
- test/unit/test_command_map.rb
`PrefixProvider#[]` could return `nil` in multi-threaded scenarios due to a race condition involving `||=`, which is not an atomic operation in JRuby.
The test that I added failed with JRuby 9.0.4.0 before the fix; now it passes.
Fixes https://github.com/capistrano/capistrano/issues/1528
> Fix race condition in CommandMap#prefix

- CHANGELOG.md
- README.md
- lib/sshkit/backends/connection_pool.rb
- test/unit/backends/test_connection_pool.rb
Ref: https://github.com/capistrano/sshkit/issues/326
By profiling capistrano, it occurred that connection pruning was a significant performance hotspot.
See https://github.com/capistrano/sshkit/issues/326#issuecomment-178939657
> After investigation it's clear that the ConnectionPool put way to much zeal into pruning expired connection.
> The prune_expired method that iterates over all the connections is called both on checkin and on checkout, so it's executed twice per host and per command.
> e.g. if you execute 5 commands, on 10 servers, it will be executed 2 * 5 * 10, 100 times! Also note that it synchronize a mutex, so it's very probable that it kills limits the concurrency.
So much that 12% of the execution time (on a micro benchmark but still) was spent checking expirations.
I think …
> Allow to disable both connection pooling and pruning idependently

- CHANGELOG.md
- EXAMPLES.md
- README.md
- lib/sshkit/all.rb
- lib/sshkit/dsl.rb
- test/unit/test_dsl.rb
In https://github.com/capistrano/sshkit/pull/28 the dsl file was removed from the original requires - I assume since the DSL was also automatically included in the context it was required in.
If I want to load the DSL _and_ use it in another context than required in, the current inclusion pattern for the DSL leaves no options - the DSL gets auto-included wherever I require it.
This leads to code like:
```ruby
require 'sskit'
module MyModule
class ClassUsingDSL
require 'sshkit/dsl'
#...
end
end
```
which is suboptimal. We can require the dsl with all other files and make the include optional instead, which allows for:
```ruby
require 'sshkit'
module MyModule
class ClassUsingDSL
include SSHKit::DSL
#...
end
end
```
The required changes are in this PR.
> Do not include SSHKit::DSL in the context it is required in

- CHANGELOG.md
- README.md
- lib/sshkit/backends/connection_pool.rb
- lib/sshkit/backends/connection_pool/cache.rb
- lib/sshkit/backends/connection_pool/nil_cache.rb
- lib/sshkit/backends/netssh.rb
- test/unit/backends/test_connection_pool.rb
This is a rewrite of SSHKit's ConnectionPool. The advantages of this version are:
* Cleaner API
* Less mutex locking
* Asynchronous connection eviction/closing
* Faster (hopefully)
```ruby
entry = pool.checkout(host, username, &Net::SSH.method(:start))
begin
ensure
pool.checkin(entry)
end
pool.with(Net::SSH.method(:start), host, username) do |connection|
end
```
Previously, every `checkin` and `checkout` would use a mutex to lock the *entire* pool every time. Now, each unique connection key has its own separate mutex, so any locking is done *per host*, and not for the entire pool.
Previously, every `checkin` and `checkout` would trigger an expiration check for *all connections* in the pool. Thus every thread must potentially wait for connections used by other threads to be cleaned up and …
> Rewrite ConnectionPool for efficiency

- CHANGELOG.md
- lib/sshkit/command_map.rb
- test/unit/test_command_map.rb
so this example works properly:
```ruby
SSHKit.config.command_map[:bundle] = -> { "#{fetch(:ruby_cmd)} /usr/bin/local/bundle" }
```
> allow procs as command map values

- lib/sshkit.rb
- lib/sshkit/backends/connection_pool.rb
- lib/sshkit/backends/connection_pool/cache.rb
- lib/sshkit/backends/netssh.rb
- lib/sshkit/configuration.rb
- lib/sshkit/host.rb
Rake 11 shipped with warnings enabled by default. These are only some of warnings on require and aren't breaking anything, but might as well clean them up.
```
lib/sshkit.rb:14: warning: method redefined; discarding old config
lib/sshkit/host.rb:130: warning: character class has duplicated range: /[@|\[|\]]/
lib/sshkit/configuration.rb:33: warning: method redefined; discarding old output_verbosity
lib/sshkit/configuration.rb:37: warning: method redefined; discarding old output_verbosity=
lib/sshkit/backends/connection_pool.rb:83: warning: private attribute?
lib/sshkit/backends/connection_pool.rb:83: warning: private attribute?
lib/sshkit/backends/connection_pool/cache.rb:58: warning: private attribute?
lib/sshkit/backends/connection_pool/cache.rb:58: warning: private attribute? …
```
> Silence interpreter warnings

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
This fixes the `zlib(finalizer): the stream was freed prematurely` warning that is printed by net-ssh when Ruby exits without closing the SSH connection first.
Fixes #342.
I could have placed the `at_exit` registration inside `ConnectionPool#initialize` (as I [originally suggested](https://github.com/capistrano/sshkit/issues/342#issuecomment-210202285)), but then that would mean all instances of ConnectionPool would never be garbage collected (the `at_exit` block would retain a reference to `self`). Doing it in the `Netssh` class definition seemed like a better place to put it.
/cc @leehambley @mfazekas
> Explicitly close the connection pool using at_exit

- EXAMPLES.md
Parameter -d  return true value if path exists and is a directory. So for file we should use -f.
[ -f /some/file ] returns true when file exists, so statement branches should be switched.
> Fixed documentation

- lib/sshkit/backends/abstract.rb
In the SSHKit Abstract backend, the 'with' method declared an instance variable (@_env) that was only used in that method, and ensured it was unset before returning. This would cause errors when nesting 'with' calls, as the outer call would try to use and then unset @_env after the inner call already unset it. It has been changed to a regular local variable, as the desired behaviour is identical to using a local variable anyway.
This fixes Issue #43 and Issue #176
> Change @_env to local variable

- lib/sshkit/command.rb
On ruby-head, Fixnum and Bignum are Unified.
https://github.com/ruby/ruby/commit/f9727c12cc8fbc5f752f5983be1f14bb976e5a13
And capistrano fail with this error when use ruby-head 
```
NoMethodError: undefined method `>=' for nil:NilClass
```
This patch will support both old and new ruby.
> Support future ruby

- CHANGELOG.md
- lib/sshkit/formatters/pretty.rb
- test/unit/formatters/test_pretty.rb
The original intent was pretty obviously to have the log level right-justified in a six-width column - this works great in the non-colorized tests - but the non-printing characters for colorization are counted as part of the level string's length, breaking the alignment.  Padding before colorizing dodges the problem.
Let me know if there's anything else I can / should do!
> Fix colorized log alignment.

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
Should fix https://github.com/capistrano/sshkit/issues/357
Disclaimer: I haven't had the time to test it properly yet.
> Add check for :known_hosts support in net-ssh

- CHANGELOG.md
- lib/sshkit/host.rb
Make sure that `Host#keys` always returns an array, avoiding https://github.com/capistrano/sshkit/issues/359
> Fix for #359

- README.md
Hello! This is a very minor pull request to fix the readme on how `as()` works. It caused us some confusion, so I figured this might help someone else.
> Updated README on how as() works

- lib/sshkit/backends/abstract.rb
Upgrading to RuboCop 0.43.0 revealed a new lint warning about an "unnecessary splat operator". I've fixed it.
> Fix "unnecessary splat" violation in RuboCop 0.43

- CHANGELOG.md
- lib/sshkit/command.rb
- test/unit/test_command.rb
@leehambley Following on from the discussion in #264.
`user` also runs the environment variables through `sprintf`, so I've applied the same fix there.
> Use string interpolation for environment variables to avoid escaping issues with sprintf

- CHANGELOG.md
- lib/sshkit/command_map.rb
`exec` is a shell builtin so `/usr/bin/env exec` results in `/usr/bin/env: exec: No such file or directory`
> do not prefix exec

- .travis.yml
- CHANGELOG.md
- Dangerfile
- sshkit.gemspec
Add Danger to SSHKit, just like we recently did in https://github.com/capistrano/capistrano/pull/1795.
"Danger" is a gem that automatically runs certain sanity checks against GitHub pull requests. Whenever an SSHKit PR is opened, Danger will check whether a CHANGELOG entry was included, and whether tests were included, and add a comment to the PR if there are violations.
> Set up Danger!

- CONTRIBUTING.md
Clarify in `CONTRIBUTING.md` that Capistrano-related support and how-to questions should be directed to Stack Overflow.
I created this PR because we were missing this topic from our contribution guidelines, as mentioned here: https://github.com/capistrano/sshkit/issues/375#issuecomment-255774226
> Capistrano support is done on Stack Overflow

- test/unit/backends/test_connection_pool.rb
- test/unit/test_command.rb
- test/unit/test_host.rb
This PR fixes the following Minitest warnings:
```
Use assert_nil if expecting nil from test/unit/test_host.rb:78:in `test_arbitrary_host_properties'. This will fail in MT6.
Use assert_nil if expecting nil from test/unit/test_command.rb:221:in `test_setting_exit_status'. This will fail in MT6.
```
Also fix a buggy test in `test_connection_pool.rb`.
> Fix `Use assert_nil if expecting nil` Minitest warnings

- CHANGELOG.md
- README.md
- lib/sshkit/configuration.rb
- lib/sshkit/coordinator.rb
- test/unit/test_configuration.rb
- test/unit/test_coordinator.rb
The `SSHKit.config.default_runner` configuration option has the ability to set the default runner, but users cannot configure the default runner.  This adds the `SSHKit.config.default_runner_config` setting, that a user can use to configure the runner.
For example, a user might want to override the default group size of 2 in the following manner:
```ruby
SSHKit.config.default_runner = :groups
SSHKit.config.default_runner_config = { limit: 10 }
```
> Ability to specify default runner config

- CHANGELOG.md
- lib/sshkit/runners/parallel.rb
- lib/sshkit/runners/sequential.rb
- test/unit/runners/test_group.rb
- test/unit/runners/test_parallel.rb
- test/unit/runners/test_sequential.rb
Prior to this PR, any Ruby StandardError (such as socket connection errors) would not be rescued or interpreted by SSHKit. In a scenario where you are running commands on multiple hosts, this meant the error would be devoid of any context, like on which host the error occurred.
This behavior was actually a mistake: we were intending to rescue and wrap all Ruby StandardErrors, but the rescue clause was written such that it only caught `SSHKit::StandardError`, which is something entirely different.
Fix this by referring to the correct constant, and add unit tests.
Fixes #389.
> Properly wrap Ruby StandardError w/ add'l context

- CHANGELOG.md
- lib/sshkit/backends/local.rb
- test/functional/backends/test_local.rb
When `recursive` optionfor `upload!` method is true, `local` argument is likely to be a String representing a directory, but `FileUtils.cp` doesn't accept it. So here we use `FileUtils.cp_r` instead.
> Use cp_r in local backend with recursive option

- CHANGELOG.md
- lib/sshkit/backends/connection_pool.rb
- lib/sshkit/backends/connection_pool/cache.rb
- lib/sshkit/backends/connection_pool/nil_cache.rb
- lib/sshkit/backends/netssh.rb
- test/functional/backends/test_netssh.rb
- test/unit/backends/test_connection_pool.rb
`args.to_s` is used for cache key of connection pooling.
`ssh_options` in `args` is changed while creating connections in
`connection_factory.call(*args)`.
Resetting cache key using changed `args` prevents cache miss.
This is a workaround for #369.
> Fix open two connections with changed cache key

- CHANGELOG.md
- lib/sshkit/backends/netssh.rb
net-ssh < 4.0.0 doesn't have Net::SSH.aassing_defaults.
Fallback to logger assignment.
https://github.com/net-ssh/net-ssh/blob/v3.2.0/lib/net/ssh.rb#L211
Fix for #396 
I've confirmed `rake test:units` with net-ssh 3.2.0.
> Fix net-ssh default options with net-ssh < 4.0.0

- lib/sshkit/command.rb
- test/unit/test_command.rb
I was browsing the `command.rb` code and found a `sanitize_command!` method that was way more complicated than it needed to be. This PR refactors it to a one-liner. I also added a missing unit test.
> Simplify code used to sanitize command

- Rakefile
- sshkit.gemspec
Fixes this RuboCop violation:
```
Rakefile:1:1: W: Lint/ScriptPermission: Script file Rakefile doesn't have execute permission.
^^^^^^^^^^^^^^^^^^^
```
I also pinned the RuboCop version to prevent new releases of RuboCop from breaking the build.
> Fix RuboCop failure in master due to inappropriate shebang in Rakefile

- CHANGELOG.md
- EXAMPLES.md
- Gemfile
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
I've been using sshkit to automate some deployment tasks recently and found the tasks would be easier if `upload!` and `download!` respected my `within(...)` context.
They already seem to work with remote relative paths which use the remote cwd, but don't respect the `within(...)` path stack. But we can just prepend `pwd_path` to remote path if it's relative to make it work.
This might be a breaking change for some users, although the documentation does say to always use absolute paths.
Also I have no idea how to test this, beyond doing a whole bunch of manual testing against a real ssh remote. 😅
> Teach upload! and download! to respect within(...)

- CHANGELOG.md
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
- test/functional/backends/test_local.rb
- test/functional/backends/test_netssh.rb
> call #to_s on remote so Pathnames don't go :boom:

- CHANGELOG.md
- lib/sshkit/backends/local.rb
- lib/sshkit/backends/netssh.rb
This restores the behaviour of 1.14 for relative paths used in upload! / download! It fixes the issues introduced by #408 where scripts written for the old behaviour raise an exception
> Restore ability to work with a relative path outside a `within` block

- Gemfile
Fixes this test failure: https://travis-ci.org/capistrano/sshkit/jobs/331658388
> Lock version of rbnacl-libsodium for older versions of Ruby

- CHANGELOG.md
- lib/sshkit/backends/connection_pool.rb
The PR https://github.com/net-ssh/net-ssh/pull/308/ introduced a new `known_hosts` options that sshkit uses as a default option: https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/netssh.rb#L38. It gets passed to `Net::SSH.start` at https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/connection_pool.rb#L59 through https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/netssh.rb#L176 as part of `args`. The same `args` is used to generate cache key for an established connection(https://github.com/capistrano/sshkit/blob/master/lib/sshkit/backends/connection_pool.rb#L90). Once the connection is established the default known_hosts gets populated by `Net::SSH`. `know_hosts` file can include thousands of entries. That means every time …
> Fix cache key generation performance for connection pooling

- CHANGELOG.md
- lib/sshkit/command.rb
- test/functional/backends/test_netssh.rb
- test/unit/test_command.rb
Command#group incorrectly escapes double quotes, resulting in a syntax
error when specifying the group a command should be executed as. This
issue manifested when user command quotes [changed from double quotes to
single quotes](https://github.com/capistrano/sshkit/commit/fbe177541288720e927292e4b7a6141031cd8a56#diff-4eaa2c55e6802df7b49a8e7a2f7584d5). This fix removes the double quote escaping in order to prevent a syntax error when executing the command.
This addresses issue https://github.com/capistrano/sshkit/issues/424
> Fix escaped quotes bug in Command#group

- Gemfile
- sshkit.gemspec
This fixes the following error when running `rake test:functional`:
NotImplementedError: unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
* ed25519 (>= 1.2, < 2.0)
* bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
Gem::LoadError : "ed25519 is not part of the bundle. Add it to your Gemfile."
Before:
```
Finished in 2.75947s
24 tests, 14 assertions, 1 failures, 14 errors, 0 skips
rake aborted!
Command failed with status (1)
```
After:
```
Finished in 12.09465s
24 tests, 34 assertions, 0 failures, 0 errors, 0 skips
```
Fixes #431
> Upgrade development dependencies to be compatible with net-ssh 5.0

- README.md
https://github.com/capistrano/sshkit/issues/433: Describing how to avoid the space messing up setting a env in linux.
> [issues/433] New example for redaction readme

- CHANGELOG.md
- README.md
- lib/sshkit/backends/abstract.rb
- test/unit/backends/test_abstract.rb
Currently, the default params for those methods are applied differently, and I don't think that's intended. In the case of the #test method, the default params for `verbosity` and `raise_on_non_zero_exit` are overriding the provided by the user.
It makes impossible to have important #test calls show any output. At least without an ugly and non-thread safe `SSHKit.config.output_verbosity=Logger::DEBUG`.
So the proposed PR makes them consistent, using the approach from #capture and provides a test to cover that.
The overall change is pretty small.
> Consistent verbosity configuration inside #capture and #test methods

- CHANGELOG.md
- lib/sshkit/backends/connection_pool.rb
Previously, the equality between cache.key and new_key
was evaluated outside the critical section of `caches.synchronize`.
When these 2 keys are evaluated as different by concurrent processes,
caches[cache.key] is deleted more than once and `nil` is assigned to
caches[new_key] after 1 thread passed critical section.
When `SSHKit::Backend::ConnectionPool#close_connections`
is invoked at the end of deployment, this pooled `nil` connection eventually
results in `NoMethodError` when `clear` is called.
https://github.com/capistrano/sshkit/blob/749337b70510e53cf6868b50d2882ac5fd4ebb40/lib/sshkit/backends/connection_pool.rb#L78
This patch fix the issue by evaluating equality
inside the critical section of `caches.synchronize`.
In my environment this patch have fixed the problem.
Although I …
> Fix broken thread safety by widening critical section on ConnectionPool

- CHANGELOG.md
- lib/sshkit/backends/connection_pool.rb
Fixes https://github.com/capistrano/sshkit/issues/438
The README currently states, that:
```ruby
SSHKit::Backend::Netssh.pool.idle_timeout = 0
```
will disable the cache and this can be used to mitigate potential problems from connection pooling. As described in #438 quite the opposite was the case. Connections were not cached, BUT the cache eviction loop was still started. With `idle_timeout = 0` the the eviction loop becomes a busy loop hogging one core at 100%.
This PR will skip the launch of the eviction loop (via `run_eviction_loop`) in case the cache is disabled. If the cache is disabled, there can't be any `timed_out_connections` because `silently_close_connection_later` is not used.
`find_cache` does not use `thread_safe_find_or_create_cache` if cache is disabled: …
> Fix Disabling of Connection Pool

- CHANGELOG.md
- lib/sshkit/command.rb
- test/unit/test_command.rb
In logging, the command UUID displayed in the "command start" phase was sometimes different to that displayed with the output of the command. This is because the backend can call `.with_redaction` on a command when logging the start, and this causes the command to be duplicated. However, if the `uuid` method hadn't been called before that point, the copy command would generate its own UUID, distinct from the original command.
This change avoids that by eagerly calculating the UUID when the command is created, so that any copied objects share the same UUID.
Fixes #454
> Ensure UUID of command is shared when redacted

- CHANGELOG.md
- lib/sshkit/host.rb
- test/unit/test_host.rb
Fixes https://github.com/capistrano/sshkit/issues/403
> Handle IPv6 addresses without port

- .travis.yml
- test/functional/backends/test_netssh.rb
- test/support/vagrant_wrapper.rb
I noticed that functional tests (`rake test:functional`) are failing on master. This PR fixes them with the following commits:
1. Strict host key checking causes functional tests to fail if the vagrant SSH server is not yet in the developer's known_hosts file. To avoid this problem, explicitly disable host key checking for functional tests.
2. PR #453 changed how commands were escaped but did not update the functional tests to match. Two functional tests were failing as a result. This commit fixes those tests.
I also made a change to `.travis.yml` as an optimization. Normally Travis CI runs builds twice on PRs, once for the push to the branch, and another for the PR itself. This is redundant and causes PRs checks to take longer that necessary. Fix this by restricting "push" builds to the …
> Fix functional tests

- README.md
- use more obvious `RAILS_ENV: :production` old one made me wonder "what does this even do, is this the ENV why is it not uppercase"
- use more obvious `execute :rake`, misleading users into thinking all kinds of commands are prefdefined is bad, show them the general purpose tools
- reduce example from 3->2 that's enough to show how it's done
- remove `wait: 5` rarely used argument and users can just use builtin `sleep 5` if they want it
- use simpler array syntax to not confuse
> improve readme example

- CHANGELOG.md
- README.md
- examples/simple_connection.rb
- lib/sshkit/backends/netssh.rb
- test/unit/backends/test_netssh.rb
fixes https://github.com/capistrano/sshkit/issues/456 since `verbosity: :DEBUG` does what I need
also fixed a few headings since ordering was level-2 -> level-4
@will-in-wi
> add a runnable example and document how verbosity/silence works

- README.md
The links to rubyplus.com are no longer functioning. It appears that the domain expired and is no longer a Ruby site.
> Removed dead links from README

- .rubocop.yml
- examples/simple_connection.rb
- sshkit.gemspec
Version 1.10 of the mocha gem was recently released, which is causing tests to fail in the master branch of SSHKit. Work around this for now by pinning our mocha dependency to `~> 1.9.0`.
> Pin mocha at 1.9.x to fix CI failures

- sshkit.gemspec
- test/helper.rb
- test/unit/formatters/test_pretty.rb
The undocumented behaviour that was changed in mocha v1.10.x has been reinstated in v1.11.1 albeit with deprecation warnings. Running the sshkit tests against mocha v1.11.1 (the latest version) allowed me to identify and fix two deprecation warnings, one of which was the cause of the problem in #479. I haven't attempted to run the functional tests locally, but hopefully your CI build will catch anything I've missed.
> Unpin mocha version and fix deprecation warnings for mocha v1.11.1

- lib/sshkit/command.rb
- test/functional/backends/test_local.rb
According to the doc one can pass a Hash or a Proc as a
:interaction_handler option, but only Hashes were wrapped into a
MappingInteractionHandler.
Fix this and add a test.
> Allow a Proc to be used as an interaction_handler

- test/functional/backends/test_netssh.rb
Hi @leehambley @mattbrictson 
Start working on https://github.com/capistrano/sshkit/issues/483. But I found that the local test dose not pass in my local environment (ruby version: 2.6.6 / macOS).
The `test_upload_large_file` failed to pass the test due to encoding issue.
```
...
205 tests, 3381 assertions, 0 failures, 0 errors, 0 skips
...
test_upload_large_file                                          FAIL (22.06s)
--- expected
+++ actual
@@ -1,3 +1,3 @@
-# encoding: UTF-8
- (snipped)
-#    valid: false
+# encoding: ASCII-8BIT
+#    valid: true
+ (snipped)
...
25 tests, 35 assertions, 1 failures, 0 errors, 0 skips
```
After this fix:
```
205 tests, 3381 assertions, 0 failures, 0 errors, 0 skips
...
test_upload_large_file                                          PASS (2.03s)
...
25 …
```
> fix: test_upload_large_file should open file in binary file mode

- Vagrantfile
- lib/sshkit/backends/connection_pool/cache.rb
- test/functional/backends/test_netssh.rb
Hi @leehambley 
This is the PR that aims to partially solve https://github.com/capistrano/sshkit/issues/483.
Sorry for the delay.
The change will do a simple polling (`process(0)`) to check if the connection is still alive before we reuse it. If the connection is closed by remote, the polling will get `<IOError: closed stream>` which will be caught and consider the connection is already closed. It partially fixes https://github.com/capistrano/sshkit/issues/483 since when the keepalive check fails and remote host closes the connection, the connection won't be reused.
However, it will not completely fix the issue because the keepalive packet should be responded by `ssh-kit/net-ssh` but it doesn't. This could be fixed by introducing another thread that keep pooling connections in pool so …
> Fix closed connection in pool

- .travis.yml
- Gemfile
This PR makes some minor modifications to our CI setup:
1. Add Ruby 2.6, 2.7, 3.0 to Travis CI.
2. Drop special gems from our Gemfile that supported Rubinius in CI. We haven't actually run Rubinius in CI since 2014, so these gems are definitely not needed now. One of the gems, `rubysl`, was preventing CI from working with Ruby 3.0.
> Add latest rubies to CI, including 3.0; drop rubinius CI support

- lib/sshkit/deprecation_logger.rb
There are some tests fail with messages below.
```
SSHKit::TestConfiguration
test_nil_deprecation_output                                    ERROR (0.00s)
Minitest::UnexpectedError:         NameError: uninitialized constant SSHKit::DeprecationLogger::Set
Did you mean?  Net
/Users/colorbox/.ghq/github.com/capistrano/sshkit/lib/sshkit/deprecation_logger.rb:5:in `initialize'
/Users/colorbox/.ghq/github.com/capistrano/sshkit/lib/sshkit/configuration.rb:21:in `new'
/Users/colorbox/.ghq/github.com/capistrano/sshkit/lib/sshkit/configuration.rb:21:in `deprecation_output='
/Users/colorbox/.ghq/github.com/capistrano/sshkit/test/unit/test_configuration.rb:25:in `test_nil_deprecation_output'
```
This PR add `require 'set'` to avoid raise NameError.
> Fix test by `require 'set'`

- .github/workflows/ci.yml
- Vagrantfile
This PR adds functional test on CI withs `vagrant up` on GitHub Actions. Some VM settings updated for keep alive connection for `test_upload_large_file`.
refs: https://github.com/jonashackt/vagrant-github-actions
> Add functional test with vagrant on CI

- .github/workflows/ci.yml
Old versions of Ruby (<= 2.2) no longer work on the latest Ubuntu image.
Fix by using `ubuntu-20.04` instead of `ubuntu-latest` for old Rubies.
Also create roll-ups job called `test-all` and `functional-all` that collects the results of all the test and functional job runs for various Ruby versions into two checks that we can use for the branch protection rule.
> Fix CI failures by running Ruby <= 2.2 on older Ubuntu image

- .github/workflows/ci.yml
- Vagrantfile
- test/functional/backends/test_netssh.rb
We were using an extremely old Vagrant box for functional tests. Booting this Vagrant box would often fail with timeout errors in CI. This PR is attempt to fix the problem with the following changes:
1. Upgrade the box to [bento/ubuntu-22.10](https://app.vagrantup.com/bento/boxes/ubuntu-22.10)
2. Increase the timeout to 10 minutes
3. Rotate the GitHub Actions cache key so that we are using a fresh, empty cache for Vagrant
I also increased `MaxAuthTries` to fix authentication failures I was seeing when trying to run functional tests locally.
> CI: Use newer Vagrant box to address timeout issues

- sshkit.gemspec
This fixes the following warning when using Capistrano on Ruby 3.3:
> sshkit/backends/netssh.rb:3: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec.
> Add mutex_m dependency to fix Ruby 3.3 warning

- EXAMPLES.md
- README.md
- lib/sshkit/backends/netssh.rb
- lib/sshkit/backends/netssh/scp_transfer.rb
- lib/sshkit/backends/netssh/sftp_transfer.rb
- lib/sshkit/host.rb
- sshkit.gemspec
- test/functional/backends/netssh_transfer_tests.rb
- test/functional/backends/test_netssh.rb
- test/functional/backends/test_netssh_scp.rb
- test/functional/backends/test_netssh_sftp.rb
- test/unit/backends/test_netssh.rb
- test/unit/test_host.rb
SSHKit can now use SFTP for file transfers. The default is still SCP, but this can be changed to SFTP per host:
```ruby
host = SSHKit::Host.new('user@example.com')
host.transfer_method = :sftp
```
or globally:
```ruby
SSHKit::Backend::Netssh.configure do |ssh|
ssh.transfer_method = :sftp
end
```
Fixes #15
> Allow SFTP to be used for upload!/download! instead of SCP

- lib/sshkit/backends/netssh/sftp_transfer.rb
Old Rubies such as Ruby 2.0 resolve a version of net-sftp that does not have the `File#size` convenience method. To support these older versions, use the lower level `File#stat`, which works for versions of net-sftp all the way back to 2.1.2.
This fixes a `NoMethodError` when SFTP is used via sshkit on Ruby 2.0.
I was able to confirm this with this successful CI job: https://github.com/capistrano/sshkit/actions/runs/7373383846/job/20062512939
Fixes #528
> Support older net-sftp API for Ruby 2.0

- EXAMPLES.md
While reviewing and testing @mattbrictson 's #524, I found myself referencing `EXAMPLES.md` and noted some inaccuracies. 
_Hoping it's ok to open this PR without a corresponding issue discussing this first._
> EXAMPLES.md corrections

- test/unit/backends/test_abstract.rb
- test/unit/test_deprecation_logger.rb
Ruby head has apparently changed the formatting of back traces slightly. This PR updates the regular expressions that we use for asserting back traces, so that they work with the new format.
Fixes CI failures on master.
> Fix failing tests on ruby head

- lib/sshkit/backends/netssh/known_hosts.rb
- sshkit.gemspec
sshkit needs `Base64` for its implementation of the known hosts file parser.
Before, we were relying on net-ssh to load Base64 for us. But starting in net-ssh 7.2.2 (which was yanked), net-ssh no longer depends on the base64 gem. That means sshkit can no longer assume it will be present and loaded.
This PR fixes compatibility with net-ssh 7.2.2+ by doing the following:
- `require "base64"` to ensure the `Base64` constant is defined
- Add `base64` as a runtime dependency so that the library is guaranteed to be present
Fixes #531
> Explicitly require base64 to fix missing constant with net-ssh 7.2.2+

- lib/sshkit/backends/connection_pool/cache.rb
`closed?` calls `process` on the connection which is not safe because we have not synchronised the connection pool. Another thread might concurrently checkout the connection and start sending commands as well.
> Avoid calling closed? outside of synchronize block

- lib/sshkit/backends/netssh.rb
- lib/sshkit/backends/netssh/known_hosts.rb
- sshkit.gemspec
Just use a plain mutex instead since only `synchronize` is used.
> Drop `mutex_m` dependency

- .github/release-drafter.yml
This brings SSHKit's configuration of [Release Drafter](https://github.com/release-drafter/release-drafter) up to date with what is used [in Capistrano](https://github.com/capistrano/capistrano/blob/c30610d6a0ccb1d62fcc8a3c4b59b6d71989ed65/.github/release-drafter.yml).
- Automatically choose next version number based on PR labels
- Include "full changelog" link in generated release notes
> Improve auto-generation of release notes

- sshkit.gemspec
Fixes the following warning on Ruby 3.3.5+ and Ruby 3.4:
> sshkit-1.23.0/lib/sshkit.rb:29: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Closes #541
> Add ostruct dependency to fix warning on Ruby 3.3.5+

- sshkit.gemspec
Using sshkit on Ruby 3.4 causes the following warning to be printed:
> warning: logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
> You can add logger to your Gemfile or gemspec to silence this warning.
To avoid this warning, and to allow sshkit to work on Ruby 3.5+, this commit adds the `logger` gem as a runtime dependency to sshkit.
> Add `logger` runtime dependency to fix warning on Ruby 3.4

- sshkit.gemspec
The `rainbow` gem is a dependency of rubocop, which we use as a development dependency on this project. Previously, we were explicitly declaring rainbow as a dependency so that we could pin it at a specific version. This was done to ensure the development gems could be installed on old versions of Ruby in CI (see f57347a).
Now that sshkit no longer supports Ruby < 2.5, this workaround is no longer needed. This commit removes the explicit rainbow dev dependency.
> Remove version pin for `rainbow` dev dependency
